site_name: Design Patterns Documentation
site_description: Documentation covering design patterns implemented in flight reservation system
docs_dir: docs
repo_url: https://github.com/sambuaneesh/Reservation-System-Starter
repo_name: Design Patterns Documentation

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.footer
    - header.autohide
    - navigation.tabs
    - search.suggest
    - search.highlight
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: index.md
  - Design Patterns:
      - 'Strategy Pattern': 'design-smells/design-smell-1.md'
      - 'Factory Method Pattern': 'design-smells/design-smell-2.md'
      - 'Template Method Pattern': 'design-smells/design-smell-3.md'
      - 'Observer Pattern': 'design-smells/design-smell-4.md'
      - 'Composite Pattern': 'design-smells/design-smell-5.md'

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - tables

plugins:
  - search